# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/reader.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 600)
        font = QtGui.QFont()
        font.setFamily("Nafees [PYRS]")
        font.setPointSize(18)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Urdu, QtCore.QLocale.Pakistan))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 701, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.prevButton = QtWidgets.QToolButton(self.layoutWidget)
        self.prevButton.setArrowType(QtCore.Qt.RightArrow)
        self.prevButton.setObjectName("prevButton")
        self.gridLayout.addWidget(self.prevButton, 2, 7, 1, 1)
        self.nextButton = QtWidgets.QToolButton(self.layoutWidget)
        self.nextButton.setArrowType(QtCore.Qt.LeftArrow)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout.addWidget(self.nextButton, 2, 8, 1, 1)
        self.titleComboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nafees [PYRS]")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.titleComboBox.setFont(font)
        self.titleComboBox.setToolTip("")
        self.titleComboBox.setWhatsThis("")
        self.titleComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleComboBox.setEditable(False)
        self.titleComboBox.setObjectName("titleComboBox")
        self.gridLayout.addWidget(self.titleComboBox, 2, 5, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nafees [PYRS]")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 5, 1, 1)
        self.bookLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nafees [PYRS]")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bookLabel.setFont(font)
        self.bookLabel.setObjectName("bookLabel")
        self.gridLayout.addWidget(self.bookLabel, 0, 4, 1, 1)
        self.bookComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.bookComboBox.setBaseSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Nafees [PYRS]")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.bookComboBox.setFont(font)
        self.bookComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bookComboBox.setObjectName("bookComboBox")
        self.gridLayout.addWidget(self.bookComboBox, 2, 4, 1, 1)
        self.sourceComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.sourceComboBox.setBaseSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Nafees [PYRS]")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.sourceComboBox.setFont(font)
        self.sourceComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sourceComboBox.setObjectName("sourceComboBox")
        self.gridLayout.addWidget(self.sourceComboBox, 2, 0, 1, 1)
        self.sourceLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nafees [PYRS]")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sourceLabel.setFont(font)
        self.sourceLabel.setObjectName("sourceLabel")
        self.gridLayout.addWidget(self.sourceLabel, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(5, 1)
        self.hadithText = QtWidgets.QTextEdit(self.centralwidget)
        self.hadithText.setGeometry(QtCore.QRect(30, 120, 701, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hadithText.sizePolicy().hasHeightForWidth())
        self.hadithText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nafees [PYRS]")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.hadithText.setFont(font)
        self.hadithText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hadithText.setStyleSheet("")
        self.hadithText.setReadOnly(True)
        self.hadithText.setObjectName("hadithText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nafees [PYRS]")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.statusbar.setFont(font)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setStyleSheet("")
        self.statusbar.setLocale(QtCore.QLocale(QtCore.QLocale.Urdu, QtCore.QLocale.Pakistan))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hadith Reader"))
        self.prevButton.setStatusTip(_translate("MainWindow", "(Ctrl+P) پچھلے حدیث"))
        self.prevButton.setText(_translate("MainWindow", "..."))
        self.prevButton.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.nextButton.setStatusTip(_translate("MainWindow", "(Ctrl+N) اگلے حدیث"))
        self.nextButton.setText(_translate("MainWindow", "..."))
        self.nextButton.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.titleComboBox.setStatusTip(_translate("MainWindow", "حدیث عنوان"))
        self.titleLabel.setText(_translate("MainWindow", "عنوان"))
        self.bookLabel.setText(_translate("MainWindow", "کتاب"))
        self.bookComboBox.setStatusTip(_translate("MainWindow", "حدیث کتاب"))
        self.sourceComboBox.setStatusTip(_translate("MainWindow", "حدیث"))
        self.sourceLabel.setText(_translate("MainWindow", "حدیث"))
        self.hadithText.setStatusTip(_translate("MainWindow", "حدیث"))
        self.statusbar.setStatusTip(_translate("MainWindow", "حدیث"))
        self.actionExit.setText(_translate("MainWindow", "Settings"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
