# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/reader.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 691, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.ayatRange = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ayatRange.setFont(font)
        self.ayatRange.setObjectName("ayatRange")
        self.gridLayout.addWidget(self.ayatRange, 1, 2, 1, 1)
        self.suraLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.suraLabel.setFont(font)
        self.suraLabel.setObjectName("suraLabel")
        self.gridLayout.addWidget(self.suraLabel, 0, 0, 1, 1)
        self.ayaLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ayaLabel.setFont(font)
        self.ayaLabel.setObjectName("ayaLabel")
        self.gridLayout.addWidget(self.ayaLabel, 0, 2, 1, 1)
        self.rukuLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rukuLabel.setFont(font)
        self.rukuLabel.setObjectName("rukuLabel")
        self.gridLayout.addWidget(self.rukuLabel, 0, 1, 1, 1)
        self.suraComboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.suraComboBox.setFont(font)
        self.suraComboBox.setToolTip("")
        self.suraComboBox.setWhatsThis("")
        self.suraComboBox.setEditable(False)
        self.suraComboBox.setObjectName("suraComboBox")
        self.gridLayout.addWidget(self.suraComboBox, 1, 0, 1, 1)
        self.rukuComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.rukuComboBox.setBaseSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rukuComboBox.setFont(font)
        self.rukuComboBox.setObjectName("rukuComboBox")
        self.gridLayout.addWidget(self.rukuComboBox, 1, 1, 1, 1)
        self.nextButton = QtWidgets.QToolButton(self.layoutWidget)
        self.nextButton.setArrowType(QtCore.Qt.LeftArrow)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout.addWidget(self.nextButton, 1, 3, 1, 1)
        self.prevButton = QtWidgets.QToolButton(self.layoutWidget)
        self.prevButton.setArrowType(QtCore.Qt.RightArrow)
        self.prevButton.setObjectName("prevButton")
        self.gridLayout.addWidget(self.prevButton, 1, 4, 1, 1)
        self.gridLayout.setColumnStretch(0, 6)
        self.gridLayout.setColumnStretch(1, 1)
        self.ayatText = QtWidgets.QTextEdit(self.centralwidget)
        self.ayatText.setGeometry(QtCore.QRect(30, 110, 691, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ayatText.sizePolicy().hasHeightForWidth())
        self.ayatText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nafees [PYRS]")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.ayatText.setFont(font)
        self.ayatText.setStyleSheet("")
        self.ayatText.setReadOnly(True)
        self.ayatText.setObjectName("ayatText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Holy Quran Reader"))
        self.ayatRange.setStatusTip(_translate("MainWindow", "Range of ayas in current ruku"))
        self.ayatRange.setText(_translate("MainWindow", "1 - 7"))
        self.suraLabel.setText(_translate("MainWindow", "Sura"))
        self.ayaLabel.setText(_translate("MainWindow", "Ayas"))
        self.rukuLabel.setText(_translate("MainWindow", "Ruku"))
        self.suraComboBox.setStatusTip(_translate("MainWindow", "Sura List"))
        self.rukuComboBox.setStatusTip(_translate("MainWindow", "Ruku List"))
        self.nextButton.setStatusTip(_translate("MainWindow", "Next Ruku (Ctrl+N)"))
        self.nextButton.setText(_translate("MainWindow", "..."))
        self.nextButton.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.prevButton.setStatusTip(_translate("MainWindow", "Previous Ruku (Ctrl+P)"))
        self.prevButton.setText(_translate("MainWindow", "..."))
        self.prevButton.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.ayatText.setStatusTip(_translate("MainWindow", "Ayat Text"))
        self.statusbar.setStatusTip(_translate("MainWindow", "Holy Quran Reader"))
        self.actionExit.setText(_translate("MainWindow", "Settings"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
